# Generated by Django 5.0.4 on 2024-04-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0003_movie_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
