# Generated by Django 5.0.4 on 2024-04-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0004_alter_movie_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="currency",
            field=models.CharField(
                choices=[("E", "Euro"), ("D", "Dollars"), ("UAH", "Grivnya")],
                default="UAH",
                max_length=4,
            ),
        ),
    ]
