# Generated by Django 5.0.4 on 2024-04-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0006_alter_movie_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "Euro"), ("USD", "Dollars"), ("UAH", "Hryvna")],
                max_length=3,
            ),
        ),
    ]
