# Generated by Django 5.0.4 on 2024-04-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0007_alter_movie_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "Euro"), ("USD", "Dollars"), ("UAH", "Hryvna")],
                default="UAH",
                max_length=4,
            ),
        ),
    ]
