# Generated by Django 5.0.4 on 2024-04-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0009_movie_director_alter_movie_budget_alter_movie_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="director_email",
            field=models.EmailField(default="sugar_daddy@gmail.com", max_length=254),
        ),
    ]
