# Generated by Django 5.0.4 on 2024-04-16 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0012_movie_director"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_actor", models.CharField(max_length=100)),
                ("last_name_actor", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="movie_app.actors",
            ),
        ),
    ]
