# Generated by Django 5.0.4 on 2024-04-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0013_actors_movie_actors"),
    ]

    operations = [
        migrations.AddField(
            model_name="actors",
            name="gender",
            field=models.CharField(
                choices=[("M", "Man"), ("F", "Woman")], default="M", max_length=1
            ),
        ),
        migrations.RemoveField(
            model_name="movie",
            name="actors",
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(to="movie_app.actors"),
        ),
    ]
